### ISSUE TITLE
Output training log

### ISSUE THREAD

**Issue by yota-p** [yota-p/02-ieee-fraud-detection#3]
## Description
Currently train process is not logged. 
Thus I can't check model training process after the batch process.

## Goal
To output training log. 

## Impact
Be able to save & check training results after batch experiment.

## Tasks
- [x] Replace print() with logger_train()
- [x] Get training result(evals_result ) from model
- [x] Add stop_watch() to all methods called from Pipeline()

**Comment by yotahk** [comment]
I reviewed how to separate log files. 
I decided to output all logs to main log for watching the process and debugging. 
And output train log in tsv for analyzing in some applications.
